# domain/repository.py
from typing import Protocol, Iterable, Optional, Tuple
from datetime import date, datetime
from .models import Flight, Booking, Passenger, Payment

class FlightRepository(Protocol):
    def list(self, *, frm: Optional[str] = None, to: Optional[str] = None, day: Optional[date] = None) -> Iterable[Flight]: ...
    def get(self, flight_id: str) -> Flight: ...
    def create(self, flight: Flight) -> Flight: ...

class BookingRepository:
    def create_booking(self, booking: Booking, passengers: list[Passenger]) -> Booking: ...
    def get_booking(self, booking_id: str) -> Booking: ...
    def list_bookings(
        self,
        *,
        user_id: Optional[str] = None,
        email: Optional[str] = None,
        phone: Optional[str] = None,
        page: int = 1,
        per_page: int = 10
    ) -> tuple[list[Booking], int]: ...
    def create_payment_for_booking(self, booking_id: str, amount: int, currency: str) -> Payment: ...
    def mark_payment_paid(self, payment_id: str, raw_payload: Optional[str] = None) -> Payment: ...
    def get_payment_by_booking(self, booking_id: str) -> Optional[Payment]: ...    
